import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarTop from "./components/navbar-top/NavbarTop";
import NavbarMid from "./components/navbar-mid/NavbarMid";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Batangas.net",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-purple-950`}>
        <NavbarTop />
        <NavbarMid />
        {children}
      </body>
    </html>
  );
}
